{% set name = "templ" %}
{% set version = "0.3.819" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/a-h/templ/archive/v{{ version }}.tar.gz
  sha256: b1eb741291c4c2309d498ef458ef6fbc0eb53a31f46b2690df26e12912e4c8ac

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - templ --help

about:
  home: https://github.com/a-h/templ
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  dev_url: https://github.com/a-h/templ

extra:
  recipe-maintainers:
    - danielnachun
