{% set name = "templ" %}
{% set version = "0.3.898" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/a-h/templ/archive/v{{ version }}.tar.gz
  sha256: 7b957bab2ec9d77a1155f7134429feb832aff6684258566c46d21044bcb97104

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - templ --help

about:
  home: https://github.com/a-h/templ
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  dev_url: https://github.com/a-h/templ

extra:
  recipe-maintainers:
    - danielnachun
