{% set name = "templ" %}
{% set version = "0.3.920" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/a-h/templ/archive/v{{ version }}.tar.gz
  sha256: 2a5edc684d6af133312d5c745da6fc825f5bc73bea346ed404df233e06499573

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - templ --help

about:
  home: https://github.com/a-h/templ
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  dev_url: https://github.com/a-h/templ

extra:
  recipe-maintainers:
    - danielnachun
