schema_version: 1

context:
  version: "0.3.1020"

package:
  name: templ
  version: ${{ version }}

source:
  url: https://github.com/a-h/templ/archive/v${{ version }}.tar.gz
  sha256: 4f21ea4f1b60d65e506fa146a33a9d83d055c6f1e2e7687421f08ada6614d83c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - templ --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  homepage: https://github.com/a-h/templ
  repository: https://github.com/a-h/templ

extra:
  recipe-maintainers:
    - danielnachun
