schema_version: 1

context:
  version: "0.3.1070"

package:
  name: templ
  version: ${{ version }}

source:
  url: https://github.com/a-h/templ/archive/v${{ version }}.tar.gz
  sha256: feb6da339d812c80ee981539bf10b90f6b77946d6eec05cb6ef38b6dc2783c8b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - templ --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A golang formatter that fixes long lines
  homepage: https://github.com/a-h/templ
  repository: https://github.com/a-h/templ

extra:
  recipe-maintainers:
    - danielnachun
